[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/certs/localhost+1.pem"
        keyFile = "/etc/certs/localhost+1-key.pem"

  [[tls.certificates]]
    certFile = "/etc/certs/lundin.test+1.pem"
    keyFile = "/etc/certs/lundin.test+1-key.pem"

  [[tls.certificates]]
    certFile = "/etc/certs/kudoz.test+1.pem"
    keyFile = "/etc/certs/kudoz.test+1-key.pem"
